"""
Email Digest Agent — Demo for Runforge

Reads recent emails from Gmail inbox, creates a summary,
and sends a digest email. The send step requires human approval.

This demonstrates:
1. Gmail read (safe step) — reads inbox using connected Gmail
2. Processing (safe step) — summarizes the emails
3. Gmail send (commit step) — sends digest, pauses for approval
"""

from agent_runtime import AgentRuntime

app = AgentRuntime()


@app.agent("email-digest")
def run(ctx, input):
    """
    Main agent function.
    
    Input (optional):
        - recipient: email address to send digest to (default: self)
        - max_emails: number of recent emails to read (default: 5)
    """
    
    recipient = input.get("recipient", None)
    max_emails = input.get("max_emails", 5)
    
    # ── Step 1: Read recent emails (SAFE — no side effects) ──
    with ctx.safe_step("read_inbox"):
        ctx.log("Reading recent emails from inbox...")
        
        result = ctx.tools.gmail.read_inbox(
            max_results=max_emails,
            query="is:inbox"
        )
        
        emails = result.get("messages", [])
        ctx.log(f"Found {len(emails)} recent emails")
        
        # Store in state for next step
        ctx.state["emails"] = emails
        ctx.state["email_count"] = len(emails)
    
    # ── Step 2: Create digest summary (SAFE — just processing) ──
    with ctx.safe_step("create_digest"):
        emails = ctx.state["emails"]
        
        # Build a simple digest
        digest_lines = []
        digest_lines.append(f"📧 Email Digest — {len(emails)} recent emails\n")
        digest_lines.append("=" * 50)
        
        for i, email in enumerate(emails, 1):
            subject = email.get("subject", "(no subject)")
            sender = email.get("from", "unknown")
            snippet = email.get("snippet", "")[:100]
            date = email.get("date", "")
            
            digest_lines.append(f"\n{i}. {subject}")
            digest_lines.append(f"   From: {sender}")
            digest_lines.append(f"   Date: {date}")
            if snippet:
                digest_lines.append(f"   Preview: {snippet}...")
        
        digest_lines.append("\n" + "=" * 50)
        digest_lines.append("Generated by Runforge Email Digest Agent")
        
        digest_text = "\n".join(digest_lines)
        ctx.state["digest"] = digest_text
        ctx.log(f"Created digest with {len(emails)} entries")
        
        # Save as artifact for the dashboard
        ctx.artifact(
            "email-digest.txt",
            digest_text,
            content_type="text/plain"
        )
    
    # ── Step 3: Send digest email (COMMIT — requires approval) ──
    with ctx.commit_step(
        "send_digest",
        description=f"Send email digest to {recipient or 'self'}",
    ):
        digest = ctx.state["digest"]
        email_count = ctx.state["email_count"]
        
        # If no recipient specified, send to self
        send_to = recipient or "me"
        
        ctx.log(f"Sending digest to {send_to}...")
        
        ctx.tools.gmail.send_email(
            to=send_to,
            subject=f"Your Email Digest — {email_count} emails summarized",
            body=digest
        )
        
        ctx.log(f"Digest sent successfully to {send_to}")
    
    return {
        "status": "success",
        "emails_processed": ctx.state["email_count"],
        "recipient": recipient or "self"
    }
